version: '3'

services:
  app:
    image: jftecnologia/laravel:8
    restart: unless-stopped
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mysql:8
    restart: unless-stopped
    ports:
      - 3310:3306
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: newamazing
      MYSQL_USER: newamazing
      MYSQL_PASSWORD: newamazing
      MYSQL_DATABASE: newamazing